# Generated by Django 3.2.1 on 2024-05-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_deliveryorder_deliver_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='item',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
    ]
